### ISSUE TITLE
`/swap/:outputCurrency` does not work

### ISSUE THREAD

**Issue by adamazad** [levelkdev/dxswap-dapp#561]
The output currency is not set in the field.

**Comment by denciu** [comment]
Workaround for now  is to add `chainId` query string to the link leading to `/swap/:outputCurrency`.

Example:

```ts
// Instead
<Link to='/swapr/0x0000'/>

// Do (location.search with chainId is now spreaded
<Link to={(location:Location) => ({...location, pathname: '/swapr/0x0000'})/>
```

**Comment by 0xVenky** [comment]
This is fixed right already in Beta 10? 🤔  @adamazad @denciu

**Comment by denciu** [comment]
> This is fixed right already in Beta 10? thinking @adamazad @denciu

This feature should allow user to prefill swap box with token by entering appropriate url in the browser (`/swapr/0x[token.address]`) however it doesn't work properly and I still don't know the reason after spending some time debugging.

We can, however, achieve same behavior programatically, so that clicking 'Get SWPR' redirects user to prefilled swap box.

To conclude - **no**, it's still not fixed and user can't use this feature but redirects in code that use this mechanism are gonna work properly.

**Comment by 0xVenky** [comment]
Closing this for now, seems to work within the code when we redirect and that is enough for now. :)
